# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define "docker-practice" do |docker|
  docker.vm.box = "docker_handson"
  docker.vm.hostname = "docker-practice"
  docker.vm.network :private_network, ip: "192.168.29.100"

  config.vm.provider "virtualbox" do |v|
  		v.memory = 2048
  end
end

end
