# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define "docker-handson-solution" do |base|
  base.vm.box = "docker-handson"
  base.vm.hostname = "docker-handson-solution"

  base.vm.provision :shell, :path => "provision.sh"
  base.vm.network :private_network, ip: "192.168.29.100"

  config.vm.provision "file", source: "files/tomcat/Dockerfile", destination: "tomcat/Dockerfile"
  config.vm.provision "file", source: "files/tomcat/handson.war", destination: "tomcat/handson.war"

  config.vm.synced_folder "files/", "/files"

  config.vm.provider "virtualbox" do |v|
  		v.memory = 1536
  end
end

end
