# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define "docker-handson-base" do |base|
  base.vm.box = "precise64"
  base.vm.hostname = "docker-handson-base"
  base.vm.box_url = "http://files.vagrantup.com/precise64.box"

  base.vm.provision :shell, :path => "provision.sh"
  base.vm.network :private_network, ip: "192.168.29.100"

  config.vm.provider "virtualbox" do |v|
  		v.memory = 2048	  
  end
end

end
